### PR TITLE
WIP: Allow signed integers

### PR DESCRIPTION
**Pull request by cbenhagen**

### CODE REVIEW

**Comment by cbenhagen** [comment]
Guess I have been a bit fast with this PR. It does not work as intended.

**Comment by cbenhagen** [comment]
Filed a bug in flutter: https://github.com/flutter/flutter/issues/21874

**Comment by codegrue** [comment]
Please let me know when this pull request if functional.

**Comment by cbenhagen** [comment]
Sure, it depends on the mentioned issue.

**Comment by codegrue** [comment]
I'm closing this until the base issue is fixed

**Pull request closed without merging**
