### PR TITLE
Editing CardSettingsDatePicker

### PR DESCRIPTION
**Pull request by Bujupah**
Adding the current app theme to datepicker.
Adding time picker if justDate = false and formatting the value depends on this last.

```dart
showDatePicker(
  context: context,
  initialDate: value ?? DateTime.now(),
  firstDate: _startDate,
  lastDate: _endDate,
  builder: (BuildContext context, Widget child) {
    return Theme(
      data: Theme.of(context),
      child: child,
    );
  }).then((_value) async {
    if(!widget.justDate){
      TimeOfDay selectedTime = await showTimePicker(
        context: context,
        initialTime: value != null 
          ? TimeOfDay(hour: value.hour, minute: value.minute) 
          : TimeOfDay.now(),
        builder: (BuildContext context, Widget child) {
          return Theme(
            data: Theme.of(context),
            child: child,
          );
        });
        _value
          ..add(Duration(
            hours: selectedTime.hour,
            minutes: selectedTime.minute,
          ));
    }
    if (_value != null) {
      didChange(_value);
      if (widget.onChanged != null) widget.onChanged(_value);
    }
  });
}
```

### CODE REVIEW

**Comment by codegrue** [comment]
Can you explain the issue with Theme that this is solving? The picker should be automatically inheriting the theme by default.

**Comment by codegrue** [comment]
And why are you not using the TimePicker for time only?

**Comment by Bujupah** [comment]
Case if you want to get the date and time at the same time, I am not sure if justDate meant for that, but switching it true or false won't effect or change anything (on the android side) that's why I added a TimePicker just after picking the date when justDate is false a TimePicker will popup... and for the Picker theme I find out that it does not inherit it from the app and instead It use a default one.

**Comment by codegrue** [comment]
I would rather have a new control called DateTimePicker that does both, to remove confusion. Would you be able to change your PR to have that new widget?

**Comment by Bujupah** [comment]
It's a pleasure.

**Pull request closed without merging**
