### PR TITLE
Feature/disable label

### PR DESCRIPTION
**Pull request by esskar**
this feature disables the label when the CardSettings-Input-Widgets are disabled

### CODE REVIEW

**Comment by codegrue** [comment]
Can you please mention this (and future) pull requests in the CHANCELOG.md file?

start a section for 1.9.9 - TBD

**Comment by codegrue** [comment]
A unit test for labelStyle would be great also

**Comment by esskar** [comment]
will do.

**Comment by codegrue** [comment]
I added the unit test

**Pull request merged**
